update v5.0
valentinoarballo/tuxchange-bootstrap pull request #39
Opened 2023-06-22 01:53 UTC by valentinoarballo

- better footer

2023-06-22 17:20 UTC, nazabucciarelliITEC requested changes
Don't you have to do this merge into main after the other pull request be accepted? Many changes won't apply on main on this way

2023-06-22 17:46 UTC, FacundoEsteban-Lemo approved these changes

2023-06-22 18:10 UTC, nazabucciarelliITEC approved these changes

2023-06-24 04:57 UTC, LucaPetrocchi approved these changes

2023-06-24 04:57 UTC, merged